"""Example output for every bot command, produced by the bot's own renderers.

The shapes here are not mocked up. Each one is generated by calling the real
function in slack_blocks.py that Slack receives its message from, so if the
renderer changes the page changes with it.

What IS invented is the data fed in: the names are fictional and the numbers
are plausible rather than real. A page that anyone can open cannot carry a
child's accuracy history, and a screenshot of a real thread would be worse.
Every block is labelled as a sample on the page.

Writes /tmp/promo/bot_examples.json.
"""
import json
import os
import re
import sys

BACKEND = os.path.expanduser("~/Desktop/TimeBack/backend")
sys.path.insert(0, BACKEND)
os.chdir(BACKEND)
import slack_blocks as B                                          # noqa: E402

OUT = "/tmp/promo/bot_examples.json"


def to_text(blocks):
    """Slack blocks -> the text a person reads in the channel."""
    out = []
    for b in blocks:
        t = b.get("type")
        if t == "header":
            out.append(("h", b["text"]["text"]))
        elif t == "divider":
            out.append(("hr", ""))
        elif t == "context":
            out.append(("dim", " ".join(e.get("text", "") for e in b.get("elements", []))))
        elif t == "section" and b.get("fields"):
            pairs = [f["text"] for f in b["fields"]]
            out.append(("fields", "\n".join(pairs)))
        elif t == "section":
            out.append(("p", b["text"]["text"]))
    return out


SAMPLES = {
 "interventions": ("interventions", B.render_interventions, {
   "scope": "Maya Okonkwo", "email": "maya.okonkwo@alpha.school",
   "include_completed": True, "include_unapproved": True,
   # Only the fields render_interventions actually reads. An earlier version of
   # this sample passed approval_notes, which the renderer ignores — so the
   # example looked thinner than the real reply.
   "rows": [
     {"created_at": "Sep 19", "type": "Custom plan", "subject": "Reading",
      "approval": "Approved", "completed": False,
      "reason": "Stuck on inference questions across three articles; accuracy fell to 61%.",
      "subject_dri": "A. Klechenko"},
     {"created_at": "Sep 12", "type": "Scaffolding plan", "subject": "Reading",
      "approval": "Approved", "completed": True,
      "reason": "Needs sentence-level support before the G5 comprehension set.",
      "subject_dri": "A. Klechenko",
      "action_taken": "Built a 6-lesson sentence scaffold and assigned it ahead of the G5 set.",
      "completed_at": "Sep 15", "minutes_spent": 25},
     {"created_at": "Sep 04", "type": "Placement change", "subject": "Math",
      "approval": "Rejected", "completed": False,
      "reason": "Guide asked to move up a grade; mastery test sat at 71%.",
      "campus_dri": "B. Rodrigues"},
   ]}),

 "student_deep_dive": ("deep dive", B.render_deep_dive, {
   "name": "Maya Okonkwo", "school": "alpha school austin", "grade": 5,
   "guide": "J. Alvarez", "status": "red", "status_label": "Needs attention",
   "metrics": {"avg_xp": 28.4, "avg_min": 96, "accuracy": 71.2,
               "xp_per_min": 0.30, "active_days": 14, "total_xp": 398},
   "dormancy": [{"subject": "Science", "dormant": True, "days_since": 11,
                 "last_active": "Sep 11", "accuracy": 68}],
   "weakest_subjects": [{"subject": "Reading", "accuracy": 61, "questions": 214},
                        {"subject": "Language", "accuracy": 69, "questions": 180}],
   "repeated_missed_skills": [{"skill": "Drawing inferences from text", "times": 6},
                              {"skill": "Main idea and supporting detail", "times": 4}],
   "working_grades": {"Math": 4, "Reading": 5, "Language": 5},
   "assigned_tests": [{"subject": "Reading", "grade": "G5", "status": "assigned",
                       "attempt_number": 2}],
   "anti_patterns": [{"label": "Rushing", "detail": "12s median on a 45s lesson"}]}),

 "student_lessons": ("lessons", B.render_lessons, {
   "student": "Maya Okonkwo", "threshold": 80, "total_named": 46,
   "window": "Sep 1 – Sep 23",
   "rows": [
     {"subject": "Reading", "kind": "lesson", "accuracy": 54,
      "lesson": "Inference: what the text implies", "questions": 22, "sittings": 3},
     {"subject": "Reading", "kind": "lesson", "accuracy": 66,
      "lesson": "Main idea across paragraphs", "questions": 18, "sittings": 2},
     {"subject": "Reading", "kind": "test", "accuracy": 71,
      "lesson": "Alpha ELA STAAR G5.2019", "questions": 34, "sittings": 1},
     {"subject": "Language", "kind": "lesson", "accuracy": 62,
      "lesson": "Subject–verb agreement", "questions": 20, "sittings": 2},
   ]}),

 "most_concerning": ("most concerning", B.render_concerning, {
   "school": "alpha school austin", "start_date": "Sep 16", "end_date": "Sep 23",
   "students": [
     {"student": "Maya Okonkwo", "status": "red", "status_label": "Needs attention",
      "avg_xp": 28.4, "avg_min": 96, "accuracy": 71.2,
      "doom_detail": [{"subject": "Reading", "grade": 5, "fails": 3}],
      "weakest_subject": {"subject": "Reading", "accuracy": 61, "questions": 214},
      "repeated_missed_skills": [{"skill": "Drawing inferences", "times": 6}],
      "anti_patterns": [{"label": "Rushing", "detail": "12s median on a 45s lesson"}]},
     {"student": "Theo Brandt", "status": "amber", "status_label": "Watch",
      "avg_xp": 41.0, "avg_min": 74, "accuracy": 83.0,
      "false_green_why": "XP on target, but all of it from one app",
      "weakest_subject": {"subject": "Math", "accuracy": 74, "questions": 160}},
   ]}),

 "doom_loops": ("doom loops", B.render_doom_loops, {
   "school": "alpha school austin",
   "loops": [
     {"student": "Maya Okonkwo", "subject": "Reading", "grade": "G5", "fail_count": 3,
      "school": "alpha school austin",
      "rows": [{"test_name": "Alpha ELA STAAR G5.2019"},
               {"test_name": "Alpha ELA STAAR G5.2019"},
               {"test_name": "Alpha ELA STAAR G5.2019"}]},
     {"student": "Theo Brandt", "subject": "Math", "grade": "G4", "fail_count": 2,
      "school": "alpha school austin",
      "rows": [{"test_name": "Alpha Math STAAR G4.2017"},
               {"test_name": "Alpha Math STAAR G4.2021"}]},
   ]}),

 "tests_taken": ("tests taken", B.render_test_list, {
   "title": "Tests taken — Alpha School Austin",
   "subtitle": "4 results · Sep 22",
   "rows": [
     {"student": "Maya Okonkwo", "test_name": "Alpha ELA STAAR G5.2019",
      "subject": "Reading", "grade": "G5", "result": "Fail", "score": 71,
      "attempt_number": 3},
     {"student": "Theo Brandt", "test_name": "Alpha Math STAAR G4.2021",
      "subject": "Math", "grade": "G4", "result": "Pass", "score": 92,
      "attempt_number": 1},
   ]}),

 "assigned_tests": ("assigned tests", B.render_test_list, {
   "title": "Assigned tests — Alpha School Austin",
   "subtitle": "3 outstanding",
   "rows": [
     {"student": "Maya Okonkwo", "test_name": "Alpha ELA STAAR G5.2021",
      "subject": "Reading", "grade": "G5", "status": "assigned", "attempt_number": 4},
     {"student": "Theo Brandt", "test_name": "Alpha Math STAAR G5.2015",
      "subject": "Math", "grade": "G5", "status": "assigned", "attempt_number": 1},
   ]}),
}


def main():
    out = {}
    for tool, (label, fn, payload) in SAMPLES.items():
        blocks = fn(payload)
        out[tool] = {"label": label, "blocks": to_text(blocks)}
        print(f"{tool:<20} {len(blocks):>2} blocks")
    os.makedirs("/tmp/promo", exist_ok=True)
    json.dump(out, open(OUT, "w"), indent=1)
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
